parameters:
#    brs_deploy.example.class: BRS\DeployBundle\Example

services:
#    brs_deploy.example:
#        class: %brs_deploy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
